### ISSUE TITLE
SSDiPharmacy - Cập nhật danh mục hàng hóa

### ISSUE THREAD

**Issue by quyngoxuan** [SSDiPharm/Plan_11-2016#3]
- Thêm 5 trường dữ liệu (Tên thuốc gốc{string}, đường dùng{string}, hoạt chất {string}, xuất xứ{int}, nhà sản xuất{int})
- Thêm danh mục xuất xứ (Id{int},Mã{string},Tên{string},Ngaytao{date})
- Thêm danh mục nhà sản xuất (Id{int},Mã{string},Tên{string},Ngaytao{date})

**Comment by acayvn** [comment]
Cập nhật danh mục hàng hóa #3 đã hoàn thành

**Comment by quyngoxuan** [comment]
- Update lại tabindex cho form danh mục hàng hóa
- Trong danh mục xuất xứ: Sửa nhãn Danh mục xuất xứ quốc gia thành Danh mục xuất xứ
