### ISSUE TITLE
SSDiPharmacy - Thêm mới tính năng bán lẻ từ chức năng Đơn thuốc

### ISSUE THREAD

**Issue by quyngoxuan** [SSDiPharm/Plan_11-2016#5]
1. Tại chức năng Đơn thuốc (dữ liệu chuyển từ phần mềm QLPK sang) hỗ trợ người dùng có thể lựa chọn "đơn thuốc" rồi chuyển sang chức năng "Bán lẻ"
2. Danh sách hiện thị trong chức năng Đơn thuốc: Mặc định hiện thị ngày làm việc hiện tại

**Comment by acayvn** [comment]
FAM.Pharmacy - Thêm mới tính năng bán lẻ từ chức năng Đơn thuốc to SSDiPharmacy
=>Đã hoàn thành
